# Generated by Django 6.0.6 on 2026-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
