# Generated by Django 6.0.6 on 2026-06-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
