# Generated by Django 6.0.6 on 2026-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
