# Generated by Django 6.0.6 on 2026-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_hallbooking_updated_at_labbooking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
